-- Create schema 
CREATE SCHEMA IF NOT EXISTS bookstore AUTHORIZATION postgres;
-- create table 
CREATE TABLE bookstore.books ( ISBN VARCHAR ( 17 ) PRIMARY KEY NOT NULL, title TEXT NOT NULL, author VARCHAR ( 200 ) NOT NULL, price DECIMAL(8,2)  NOT NULL, quantity INT NOT NULL);

-- Insert sample records
INSERT INTO  bookstore.books (title, author, ISBN, price, quantity ) VALUES ('Decision in Normandy','Carlo Este','978-0-060-97312-9',12.10,10); 
INSERT INTO  bookstore.books (title, author, ISBN, price, quantity ) VALUES ('Clara Callan','Richard Bruce Wright','978-0-060-97312-8',11.10,1); 
INSERT INTO  bookstore.books (title, author, ISBN, price, quantity ) VALUES ('The Kitchen God' || chr(39) || 's Wife','Amy Tan','978-0-060-97312-2',13.10,2); 
INSERT INTO  bookstore.books (title, author, ISBN, price, quantity ) VALUES ('PLEADING GUILTY','Scott Turow','978-0-060-97312-3',14.10,5); 
INSERT INTO  bookstore.books (title, author, ISBN, price, quantity ) VALUES ('Nights Below Station Street','David Adams Richards','978-0-060-97312-4',15.10,0); 

-- TEST FOR SQL QUESTION
-- CREATE SCHEMA IF NOT EXISTS autodesk AUTHORIZATION postgres;
-- CREATE TABLE autodesk.tblSubscriptionInfo(subscription_id int, product_id int, product_name varchar(200), subscription_start_date timestamp, subscription_end_date timestamp,customer_id int, customer_contact_phone varchar(200), customer_name varchar(200), customer_address varchar(200));

-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (1,1,'autocad 2022', TO_DATE('01-01-2022', 'DD-MM-YYYY'), TO_DATE('31-12-2022', 'DD-MM-YYYY'), 1, '983248314', 'John1', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (2,1,'autocad 2022', TO_DATE('02-02-2022', 'DD-MM-YYYY'), TO_DATE('29-11-2022', 'DD-MM-YYYY'), 2, '983248315', 'John2', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (3,1,'autocad 2022', TO_DATE('03-03-2022', 'DD-MM-YYYY'), TO_DATE('31-10-2022', 'DD-MM-YYYY'), 3, '983248316', 'John3', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (4,1,'autocad 2022', TO_DATE('04-04-2022', 'DD-MM-YYYY'), TO_DATE('10-09-2022', 'DD-MM-YYYY'), 4, '983248317', 'John4', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (5,1,'autocad 2022', TO_DATE('05-05-2022', 'DD-MM-YYYY'), TO_DATE('31-08-2022', 'DD-MM-YYYY'), 5, '983248318', 'John5', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (6,1,'autocad 2022', TO_DATE('06-06-2022', 'DD-MM-YYYY'), TO_DATE('31-07-2022', 'DD-MM-YYYY'), 6, '983248319', 'John6', 'SINGAPORE');
-- -- less than 3 month sub
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (7,1,'autocad 2022', TO_DATE('06-06-2022', 'DD-MM-YYYY'), TO_DATE('06-07-2022', 'DD-MM-YYYY'), 7, '983248319', 'John8', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (8,1,'autocad 2022', TO_DATE('06-06-2022', 'DD-MM-YYYY'), TO_DATE('04-09-2022', 'DD-MM-YYYY'), 7, '983248319', 'John8', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (9,1,'autocad 2022', TO_DATE('06-06-2022', 'DD-MM-YYYY'), TO_DATE('04-10-2023', 'DD-MM-YYYY'), 7, '983248319', 'John9', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (77,2,'autocad 2023', TO_DATE('01-01-2023', 'DD-MM-YYYY'), TO_DATE('01-03-2023', 'DD-MM-YYYY'),  1, '983248313', 'John1', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (87,2,'autocad 2023', TO_DATE('01-02-2023', 'DD-MM-YYYY'), TO_DATE('29-11-2023', 'DD-MM-YYYY'), 2, '983248313', 'John2', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (97,2,'autocad 2023', TO_DATE('01-03-2023', 'DD-MM-YYYY'), TO_DATE('31-10-2023', 'DD-MM-YYYY'), 3, '983248313', 'John3', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (170,2,'autocad 2023', TO_DATE('04-04-2023', 'DD-MM-YYYY'), TO_DATE('10-09-2023', 'DD-MM-YYYY'), 4, '983248313', 'John4', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (171,2,'autocad 2023', TO_DATE('05-05-2023', 'DD-MM-YYYY'), TO_DATE('31-08-2023', 'DD-MM-YYYY'), 5, '983248313', 'John5', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (172,2,'autocad 2023', TO_DATE('06-06-2023', 'DD-MM-YYYY'), TO_DATE('31-07-2023', 'DD-MM-YYYY'), 6, '983248313', 'John6', 'SINGAPORE');
-- -- more than 2 products
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (13,3,'autocad 2024', TO_DATE('06-06-2024', 'DD-MM-YYYY'), TO_DATE('31-07-2024', 'DD-MM-YYYY'), 6, '983248313', 'John6', 'SINGAPORE');
-- -- more than 1 product id
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (14,4,'maya  2022', TO_DATE('06-06-2022', 'DD-MM-YYYY'), TO_DATE('05-07-2022', 'DD-MM-YYYY'), 10, '983248323', 'John10', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (15,4,'maya  2022', TO_DATE('06-06-2022', 'DD-MM-YYYY'), TO_DATE('05-09-2022', 'DD-MM-YYYY'), 11, '983248113', 'John11', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (16,4,'maya  2022', TO_DATE('06-06-2022', 'DD-MM-YYYY'), TO_DATE('05-10-2022', 'DD-MM-YYYY'), 12, '983248123', 'John12', 'SINGAPORE');
-- -- 1 day diff between end and start date 
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (17,4,'maya  2022', TO_DATE('06-10-2022', 'DD-MM-YYYY'), TO_DATE('05-11-2022', 'DD-MM-YYYY'), 12, '983248123', 'John12', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (18,4,'maya  2022', TO_DATE('06-11-2022', 'DD-MM-YYYY'), TO_DATE('05-12-2022', 'DD-MM-YYYY'), 12, '983248123', 'John12', 'SINGAPORE');
-- -- with different product 
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (19,5,'maya  2023', TO_DATE('06-10-2023', 'DD-MM-YYYY'), TO_DATE('05-11-2023', 'DD-MM-YYYY'), 12, '983248123', 'John12', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (20,5,'maya  2023', TO_DATE('06-11-2023', 'DD-MM-YYYY'), TO_DATE('05-12-2023', 'DD-MM-YYYY'), 12, '983248123', 'John12', 'SINGAPORE');
-- -- same product 
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (271,5,'maya  2023', TO_DATE('06-10-2023', 'DD-MM-YYYY'), TO_DATE('05-11-2023', 'DD-MM-YYYY'), 13, '983248123', 'John13', 'SINGAPORE');
-- -- subscribe for higher version 
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (21,4,'maya  2022', TO_DATE('06-10-2023', 'DD-MM-YYYY'), TO_DATE('05-11-2023', 'DD-MM-YYYY'), 13, '983248123', 'John13', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (22,5,'maya  2023', TO_DATE('06-11-2023', 'DD-MM-YYYY'), TO_DATE('05-12-2023', 'DD-MM-YYYY'), 13, '983248123', 'John13', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (25,7,'meee  2022', TO_DATE('06-10-2022', 'DD-MM-YYYY'), TO_DATE('05-11-2022', 'DD-MM-YYYY'), 13, '983248123', 'John13', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (26,8,'meee  2023', TO_DATE('06-11-2023', 'DD-MM-YYYY'), TO_DATE('05-12-2023', 'DD-MM-YYYY'), 13, '983248123', 'John13', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (27,7,'meee  2022', TO_DATE('06-10-2022', 'DD-MM-YYYY'), TO_DATE('05-11-2022', 'DD-MM-YYYY'), 13, '983248123', 'John13', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (28,9,'meee  2021', TO_DATE('06-11-2021', 'DD-MM-YYYY'), TO_DATE('05-12-2021', 'DD-MM-YYYY'), 13, '983248123', 'John13', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (727,7,'meee  2022', TO_DATE('06-10-2022', 'DD-MM-YYYY'), TO_DATE('05-11-2022', 'DD-MM-YYYY'), 15, '983248123', 'John15', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (278,9,'meee  2021', TO_DATE('06-11-2021', 'DD-MM-YYYY'), TO_DATE('05-12-2021', 'DD-MM-YYYY'), 15, '983248123', 'John15', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (23,6,'maya  2021', TO_DATE('06-10-2023', 'DD-MM-YYYY'), TO_DATE('05-11-2023', 'DD-MM-YYYY'), 14, '983248123', 'John14', 'SINGAPORE');
-- INSERT INTO autodesk.tblSubscriptionInfo (subscription_id, product_id, product_name, subscription_start_date, subscription_end_date, customer_id, customer_contact_phone, customer_name, customer_address) VALUES (24,5,'maya  2023', TO_DATE('06-11-2023', 'DD-MM-YYYY'), TO_DATE('05-12-2023', 'DD-MM-YYYY'), 14, '983248123', 'John14', 'SINGAPORE');
